Repository depromeet/ticlemoa-iOS, pull requests merged in 2022-12, with the labels that each got.

#23 [Fix] Run 실패 현상 해결
  Project.swift
  Targets/API/Resources/API.plist
  Targets/API/Sources/API.swift
  Targets/API/Tests/APITests.swift
Labels: ⛔️Hotfix

#25 [Feature] 마이페이지 UI
  Targets/UserInterface/Sources/MyPageView.swift
Labels: ⚡️Feature

#21 [Feature] 태그 관리 뷰 UI 구성
  Targets/UserInterface/Sources/TagManagingView.swift
Labels: ⚡️Feature

#38 [Feature] MainTabView 구성 및 기타 컴포넌트 추가
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/add.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/add.imageset/add.svg
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/community.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/community.imageset/community.svg
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/home.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/home.imageset/home.svg
  Targets/Ticlemoa/Sources/TiclemoaApp.swift
  Targets/UserInterface/Sources/Alarm/AlarmView.swift
  Targets/UserInterface/Sources/Community/CommunityView.swift
  Targets/UserInterface/Sources/ContentView.swift
  Targets/UserInterface/Sources/Home/ArticleRow.swift
  Targets/UserInterface/Sources/Home/HomeArticleList.swift
  Targets/UserInterface/Sources/Home/HomeView.swift
  Targets/UserInterface/Sources/MainTab/MainTabView.swift
  Targets/UserInterface/Sources/MainTab/Tab.swift
  Targets/UserInterface/Sources/Profile/ProfileView.swift
  Targets/UserInterface/Sources/Utils/Collapsible.swift
  Targets/UserInterface/Sources/Utils/Extensions/Color+CustomColor.swift
  Targets/UserInterface/Sources/Utils/Fonts/Font+Extension.swift
  Targets/UserInterface/Sources/Utils/Fonts/Pretendard-Black.otf
  Targets/UserInterface/Sources/Utils/Fonts/Pretendard-Bold.otf
  Targets/UserInterface/Sources/Utils/Fonts/Pretendard-ExtraBold.otf
  Targets/UserInterface/Sources/Utils/Fonts/Pretendard-ExtraLight.otf
  Targets/UserInterface/Sources/Utils/Fonts/Pretendard-Light.otf
  Targets/UserInterface/Sources/Utils/Fonts/Pretendard-Medium.otf
  Targets/UserInterface/Sources/Utils/Fonts/Pretendard-Regular.otf
  Targets/UserInterface/Sources/Utils/Fonts/Pretendard-SemiBold.otf
  Targets/UserInterface/Sources/Utils/Fonts/Pretendard-Thin.otf
Labels: ⚡️Feature

#36 [Feature] TextField의 PlaceHolder 색상 지정기능
  Targets/UserInterface/Sources/Utils/Extensions/TextField+PlaceHolderColor.swift
Labels: ⚡️Feature

#28 [Feature] 프로필 설정 UI 및 마이페이지 UI, Navigation 설정
  Targets/UserInterface/Sources/MyPageView.swift
  Targets/UserInterface/Sources/ProfileSettingView.swift
Labels: ⚡️Feature

#43 [Feature] iOS16으로 Deployment Target 올리기
  Project.swift
Labels: ⚡️Feature

#44 [Feature] 계정삭제 Modal UI 구성
  Targets/Ticlemoa/Resources/Assets.xcassets/ColorSets/secondaryRed.colorset/Contents.json
  Targets/UserInterface/Sources/MyPageView.swift
  Targets/UserInterface/Sources/Utils/Extensions/Color+CustomColor.swift
Labels: ⚡️Feature

#42 [Feature] 태그추가 모달 구성
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/radio_off.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/radio_off.imageset/radio_off.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/radio_on.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/radio_on.imageset/radio_on.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/tag.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/tag.imageset/tag.png
  Targets/UserInterface/Sources/TagSelectingList/TagSelectingListRow.swift
  Targets/UserInterface/Sources/TagSelectingList/TagSelectingListView.swift
  Targets/UserInterface/Sources/Utils/Extensions/PresentationDetent+.swift
Labels: ⚡️Feature

#53 [Feature] 서비스 정보 UI 구성
  Targets/Ticlemoa/Resources/Assets.xcassets/Arrow.right.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/Arrow.right.imageset/Vector 108.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Arrow.right.imageset/Vector 108@2x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Arrow.right.imageset/Vector 108@3x.png
  Targets/UserInterface/Sources/MyPage/MyPageView.swift
  Targets/UserInterface/Sources/MyPage/ProfileSettingView.swift
  Targets/UserInterface/Sources/MyPage/ServiceInformationView.swift
Labels: ⚡️Feature

#60 [Feature] 마이페이지 알림설정 UI 구성
  Targets/UserInterface/Sources/MyPage/AlertSettingView.swift
  Targets/UserInterface/Sources/MyPage/MyPageView.swift
  Targets/UserInterface/Sources/Utils/TiclemoaButton.swift
Labels: ⚡️Feature

#48 [Feature] Ticlemoa CustomAlert 구성하기
  Targets/UserInterface/Sources/Utils/Components/TiclemoaAlert.swift
Labels: ⚡️Feature

#62 [Refactor] 마이페이지 UI 업데이트
  Targets/Ticlemoa/Resources/Assets.xcassets/Bell.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/Bell.imageset/icon.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Bell.imageset/icon@2x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Bell.imageset/icon@3x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Information.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/Information.imageset/icon.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Information.imageset/icon@2x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Information.imageset/icon@3x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Pen.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/Pen.imageset/icon.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Pen.imageset/icon@2x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Pen.imageset/icon@3x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/QuestionMark.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/QuestionMark.imageset/icon.png
  Targets/Ticlemoa/Resources/Assets.xcassets/QuestionMark.imageset/icon@2x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/QuestionMark.imageset/icon@3x.png
  Targets/UserInterface/Sources/MyPage/MyPageView.swift
Labels: ♻️Refactor

#65 [Feature] BottomSheet 구현
  Targets/UserInterface/Sources/Utils/BottomSheetView.swift
  Targets/UserInterface/Sources/Utils/Extensions/View+BottomSheet.swift
Labels: ⚡️Feature

#67 [Refactor] ButtomSheet 리펙토링
  Targets/UserInterface/Sources/MyPage/MyPageView.swift
  Targets/UserInterface/Sources/Utils/Extensions/PresentationDetent+.swift
Labels: ♻️Refactor

#70 [Feature] TiclemoaNavigationBar 구현
  Targets/UserInterface/Sources/Utils/Extensions/View+Extension.swift
  Targets/UserInterface/Sources/Utils/TiclemoaNavigationBar.swift
Labels: ⚡️Feature

#74 [Feature] MainTabView에서 MyPageView로 Navigation하기
  Targets/UserInterface/Sources/MainTab/MainTabView.swift
  Targets/UserInterface/Sources/Profile/ProfileView.swift
  Targets/UserInterface/Sources/Utils/DefaultProfileView.swift
Labels: ⚡️Feature

#76 [Fix] No image named 'alarm' 버그 해결
  Targets/UserInterface/Sources/MainTab/MainTabView.swift
  Targets/UserInterface/Sources/MyPage/MyPageView.swift
Labels: 🐞Bug

#46 [Feature] LoginView, HomeView 정렬 기능, Font System 추가
  Targets/Ticlemoa/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Targets/Ticlemoa/Resources/Assets.xcassets/AppIcon.appiconset/120 1.png
  Targets/Ticlemoa/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Targets/Ticlemoa/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Targets/Ticlemoa/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Targets/Ticlemoa/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Targets/Ticlemoa/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Targets/Ticlemoa/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Targets/Ticlemoa/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Targets/Ticlemoa/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Targets/Ticlemoa/Sources/TiclemoaApp.swift
  Targets/UserInterface/Sources/AddingLinkView/View/AddingLinkView.swift
  Targets/UserInterface/Sources/ContentView.swift
  Targets/UserInterface/Sources/Home/HomeArticle/Article.swift
  Targets/UserInterface/Sources/Home/HomeArticle/ArticleRow.swift
  Targets/UserInterface/Sources/Home/HomeArticle/HomeArticleList.swift
  Targets/UserInterface/Sources/Home/HomeArticleList.swift
  Targets/UserInterface/Sources/Home/HomeDummyDatta.swift
  Targets/UserInterface/Sources/Home/HomeView.swift
  Targets/UserInterface/Sources/Home/HomeViewModel.swift
  Targets/UserInterface/Sources/Home/Network/GetArticle/Article.swift
  Targets/UserInterface/Sources/Home/Network/UploadArticle/UploadArticleAPI.swift
  Targets/UserInterface/Sources/Home/Network/UploadArticle/UploadArticleRequest.swift
  Targets/UserInterface/Sources/Home/Network/UploadArticle/UploadArticleResponse.swift
  Targets/UserInterface/Sources/Login/AppleLogin/SignInWithApple.swift
  Targets/UserInterface/Sources/Login/AppleLogin/SignInWithAppleDelegates.swift
  Targets/UserInterface/Sources/Login/LoginView.swift
  Targets/UserInterface/Sources/Login/LoginViewModel.swift
  Targets/UserInterface/Sources/Login/Network/ErrorType.swift
  Targets/UserInterface/Sources/Login/Network/KakaoLogin/KakaoLoginAPI.swift
  Targets/UserInterface/Sources/Login/Network/KakaoLogin/KakaoLoginRequest.swift
  Targets/UserInterface/Sources/Login/Network/KakaoLogin/KakaoLoginResponse.swift
  Targets/UserInterface/Sources/Login/Network/Router.swift
  Targets/UserInterface/Sources/MainTab/MainTabView.swift
  Targets/UserInterface/Sources/MyPage/MyPageView.swift
  Targets/UserInterface/Sources/Utils/Collapsible.swift
  Targets/UserInterface/Sources/Utils/Extensions/ButtonStyle+Extension.swift
  Targets/UserInterface/Sources/Utils/Extensions/DateFormatter+Extensions.swift
  Targets/UserInterface/Sources/Utils/Extensions/EnvironmentValues.swift
  Targets/UserInterface/Sources/Utils/Fonts/Font+Extension.swift
  Targets/UserInterface/Sources/Utils/HapticsManager/HapticsManager.swift
  Targets/UserInterface/Sources/Utils/UserInfo/UserInfoService.swift
  Ticlemoa.entitlements
Labels: ⚡️Feature

#93 [Feature] Setup Tuist - 외부라이브러리 설정하기
  Project.swift
  Tuist/ProjectDescriptionHelpers/Extension.swift
Labels: ⚡️Feature, 💽 Request

#96 [Fix] 외부 라이브러리 적용 방식 변경
  Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Extension.swift
Labels: ♻️Refactor
