Repository depromeet/ticlemoa-iOS, pull requests merged in 2023-01, with the labels that each got.

#100 [fix] Tuist 모듈 의존성 수정
  Project.swift
  Targets/API/Sources/HTTPMethod.swift
  Targets/DomainInterface/Resources/Localizable.strings
Labels: ⛔️Hotfix

#122 [Fix] KakaoSDK 모듈 이동으로 발생한 에러처리
  Targets/Domain/Sources/Model/LoginModel.swift
  Targets/DomainInterface/Sources/Model/LoginModelProtocol.swift
  Targets/UserInterface/Sources/Login/LoginView.swift
  Targets/UserInterface/Sources/Login/LoginViewModel.swift
Labels: 🐞Bug, ⛔️Hotfix

#118 [Refactor] ModelContainer 의존성 주입 시점 변경
  Targets/Ticlemoa/Sources/TiclemoaApp.swift
  Targets/UserInterface/Sources/ContentView.swift
  Targets/UserInterface/Sources/Login/LoginView.swift
  Targets/UserInterface/Sources/Login/LoginViewModel.swift
Labels: 🙏 Help, 🙋‍♂️Question, ♻️Refactor

#86 [Feature] CustomButtomSheet에 handleBar Hidden 기능
  Targets/UserInterface/Sources/Utils/BottomSheetView.swift
  Targets/UserInterface/Sources/Utils/Extensions/View+BottomSheet.swift
Labels: ⚡️Feature

#89 [Fix] cornerRadius 버그 해결
  Targets/UserInterface/Sources/Utils/BottomSheetView.swift
Labels: 🐞Bug

#102 [Refactor] BottomSheet ViewModifier 수정
  Targets/UserInterface/Sources/AddingLinkView/View/AddingLinkView.swift
  Targets/UserInterface/Sources/MyPage/MyPageView.swift
  Targets/UserInterface/Sources/Utils/Extensions/View+BottomSheet.swift
Labels: ♻️Refactor

#103 [Refactor] ButtomSheetView 나누기, 접근제어자 수정
  Targets/UserInterface/Sources/Utils/BottomSheetView.swift
Labels: ♻️Refactor

#104 [Refactor] 공유하기 링크추가 뷰 접근제어자 수정
  Targets/UserInterface/Sources/TagSelectingList/TagSelectingListView.swift
Labels: ♻️Refactor

#105 [Refactor] ShareExtension을 UIKit에서 SwiftUI로 수정
  Targets/ShareExtension/Sources/ShareNavigationController.swift
  Targets/ShareExtension/Sources/ShareViewController.swift
Labels: ♻️Refactor

#107 [Feature] 공유하기 기능으로 ticlemoa 앱을 켜고, ShareNavigationController 실행하기
  Project.swift
  Targets/ShareExtension/Resources/Base.lproj/MainInterface.storyboard
  Targets/ShareExtension/Resources/Localizable.strings
Labels: ⚡️Feature

#115 [Feature] 모아모아 첫 진입시 보이는 BottomSheet UI 구성
  Targets/Ticlemoa/Resources/Assets.xcassets/MoamoaImage.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/MoamoaImage.imageset/image.jpg
  Targets/Ticlemoa/Resources/Assets.xcassets/MoamoaImage.imageset/image@2x.jpg
  Targets/Ticlemoa/Resources/Assets.xcassets/MoamoaImage.imageset/image@3x.jpg
  Targets/UserInterface/Sources/Community/CommunityView.swift
Labels: ⚡️Feature

#117 [Fix] BottomSheet Binding 적용
  Targets/UserInterface/Sources/Utils/BottomSheetView.swift
Labels: 🐞Bug

#128 [Feature] 폰트 파일 추가
  Targets/Ticlemoa/Resources/PretendardFont/Pretendard-Black.otf
  Targets/Ticlemoa/Resources/PretendardFont/Pretendard-Bold.otf
  Targets/Ticlemoa/Resources/PretendardFont/Pretendard-ExtraBold.otf
  Targets/Ticlemoa/Resources/PretendardFont/Pretendard-ExtraLight.otf
  Targets/Ticlemoa/Resources/PretendardFont/Pretendard-Light.otf
  Targets/Ticlemoa/Resources/PretendardFont/Pretendard-Medium.otf
  Targets/Ticlemoa/Resources/PretendardFont/Pretendard-Regular.otf
  Targets/Ticlemoa/Resources/PretendardFont/Pretendard-SemiBold.otf
  Targets/Ticlemoa/Resources/PretendardFont/Pretendard-Thin.otf
Labels: ⚡️Feature

#134 [Feature]ArticleDomain 구현 및 LoginUser 방식 변경
  Targets/API/Sources/Request/Article/CreateArticleRequest.swift
  Targets/API/Sources/Request/Login/KakaoLoginRequest.swift
  Targets/API/Sources/Response/Article/ReadArticleResponse.swift
  Targets/API/Sources/Response/Article/SearchArticleResponse.swift
  Targets/API/Tests/APITests.swift
  Targets/Domain/Sources/Entity/ArticleData.swift
  Targets/Domain/Sources/Entity/LoginUserData.swift
  Targets/Domain/Sources/Model/ArticleModel.swift
  Targets/Domain/Sources/Model/LoginModel.swift
  Targets/DomainInterface/Sources/Entity/Article.swift
  Targets/DomainInterface/Sources/Entity/LoginUser.swift
  Targets/DomainInterface/Sources/Model/ArticleModelProtocol.swift
  Targets/DomainInterface/Sources/Model/LoginModelProtocol.swift
  Targets/UserInterface/Sources/ContentView.swift
Labels: ⚡️Feature, ♻️Refactor

#136 [Feature] 홈화면 전환시, 서버로 부터 Tag 데이터 불러오는 메소드 추가
  Targets/UserInterface/Sources/Home/HomeViewModel.swift
Labels: ⚡️Feature

#138 [Refactor] pause ShareExtension
  Project.swift
  Targets/ShareExtension/Resources/Localizable.strings
  Targets/ShareExtension/Sources/ShareNavigationController.swift
Labels: ♻️Refactor

#159 [Fix] DomainInterfaceError 관련 컴파일 에러 처리
  Targets/DomainInterface/Sources/DomainInterfaceError.swift
Labels: 🐞Bug, ⛔️Hotfix

#164 [Fix] MockLoginModel protocol 함수 누락 구현
  Targets/UserInterface/Sources/ContentView.swift
Labels: 🐞Bug, ⛔️Hotfix

#144 [Refactor] MianTabView 밖의 NavigationView 위치를 내부로 변경
  Targets/UserInterface/Sources/Home/HomeView.swift
  Targets/UserInterface/Sources/Scenes/MainTab/MainTabView.swift
Labels: ♻️Refactor

#145 [Feature] 프로필 수정 화면에서 사진 설정 기능
  Targets/UserInterface/Sources/Scenes/MyPage/ProfileSetting/ProfileSettingView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/ProfileSetting/ProfileSettingViewModel.swift
Labels: ⚡️Feature

#147 [Feature] 사진을 설정하면 저장하고, 마이페이지 화면도 변경하는 기능
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageViewModel.swift
  Targets/UserInterface/Sources/Scenes/MyPage/ProfileSetting/ProfileSettingViewModel.swift
Labels: ⚡️Feature

#151 [Feature] 마이페이지에서 사용자가 닉네임을 변경하는 기능
  Targets/Domain/Sources/Model/LoginModel.swift
  Targets/DomainInterface/Sources/Model/LoginModelProtocol.swift
  Targets/UserInterface/Sources/ContentView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageViewModel.swift
  Targets/UserInterface/Sources/Scenes/MyPage/ProfileSetting/ProfileSettingView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/ProfileSetting/ProfileSettingViewModel.swift
Labels: ⚡️Feature

#152 [Feature] 계정삭제 화면 UI 업데이트
  Targets/Ticlemoa/Resources/Assets.xcassets/SadImage.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/SadImage.imageset/image.jpg
  Targets/Ticlemoa/Resources/Assets.xcassets/SadImage.imageset/image@2x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/SadImage.imageset/image@3x.png
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageView.swift
Labels: ⚡️Feature

#162 [Feature] 계정 삭제 기능
  Targets/API/Sources/Request/AccountDeletion/AccountDeletionRequest.swift
  Targets/Domain/Sources/Model/LoginModel.swift
  Targets/DomainInterface/Sources/Model/LoginModelProtocol.swift
  Targets/UserInterface/Sources/ContentView.swift
  Targets/UserInterface/Sources/Scenes/MainTab/MainTabView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageViewModel.swift
Labels: ⚡️Feature

#166 [Fix] 복사한 링크 추가하기, 검색하기 back버튼 동작하지 않는 버그 해결
  Targets/UserInterface/Sources/Scenes/MainTab/MainTabView.swift
Labels: 🐞Bug

#168 [Fix] 검색 화면에서 하단 탭바를 보이지 않게 처리
  Targets/UserInterface/Sources/Scenes/MainTab/MainTabView.swift
Labels: 🐞Bug

#177 [fix] 최근 검색어 레이블 및 전체삭제 버튼 제거
  Targets/UserInterface/Sources/Scenes/Searcing/SearchingArticleView.swift
Labels: ⛔️Hotfix, ♻️Refactor

#182 [Feature] 문의하기를 눌러 ticlemoa에 문의 메일을 보낼 수 있는 기능
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageViewModel.swift
  Targets/UserInterface/Sources/Utils/Components/MailView.swift
Labels: ⚡️Feature

#188 [Feature] 서비스 정보에서 개인정보 처리방침과 오픈소스 화면 구성
  Targets/UserInterface/Sources/Scenes/MyPage/ServiceInformation/ServiceInformationView.swift
Labels: ⚡️Feature

#190 fix: 뷰모델 주입 변경
  Targets/UserInterface/Sources/Home/HomeView.swift
Labels: 🐞Bug, ⛔️Hotfix

#194 [Feature] 아티클 수정하기를 누르면 fullScreenModal로 AddingLinkView를 띄운다
  Targets/UserInterface/Sources/Home/HomeArticle/ArticleRow.swift
Labels: ⚡️Feature

#196 [Feature] 마이페이지에서 닉네임 수정시 UI와 제약사항 설정
  Targets/UserInterface/Sources/Scenes/MyPage/ProfileSetting/ProfileSettingView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/ProfileSetting/ProfileSettingViewModel.swift
Labels: ⚡️Feature

#197 [Feature] ticlemoaNavigationBar의 UI 업데이트
  Targets/UserInterface/Sources/Utils/Components/TiclemoaNavigationBar.swift
Labels: ⚡️Feature

#198 [Feature] 프로필 설정 화면에서 하단 탭바가 보이지 않도록 처리
  Targets/UserInterface/Sources/Scenes/MainTab/MainTabView.swift
Labels: ⚡️Feature

#201 [Feature] 마이페이지 탭바 아이콘 설정
  Targets/Ticlemoa/Resources/Assets.xcassets/MypageSelected.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/MypageSelected.imageset/icon.jpg
  Targets/Ticlemoa/Resources/Assets.xcassets/MypageSelected.imageset/icon@2x.jpg
  Targets/Ticlemoa/Resources/Assets.xcassets/MypageSelected.imageset/icon@3x.jpg
  Targets/Ticlemoa/Resources/Assets.xcassets/MypageUnselected.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/MypageUnselected.imageset/icon.jpg
  Targets/Ticlemoa/Resources/Assets.xcassets/MypageUnselected.imageset/icon@2x.jpg
  Targets/Ticlemoa/Resources/Assets.xcassets/MypageUnselected.imageset/icon@3x.jpg
  Targets/UserInterface/Sources/Scenes/MainTab/MainTabView.swift
Labels: ⚡️Feature

#204 [Refactor] main runloop 추가
  Targets/Domain/Sources/Model/ArticleModel.swift
  Targets/Domain/Sources/Model/TagModel.swift
  Targets/UserInterface/Sources/AddingLinkView/ViewModel/AddingLinkViewModel.swift
  Targets/UserInterface/Sources/Home/HomeViewModel.swift
  Targets/UserInterface/Sources/Login/LoginViewModel.swift
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageViewModel.swift
Labels: ♻️Refactor

#200 [Refactor] 검색기능 QA 반영
  Targets/UserInterface/Sources/Scenes/Searcing/SearchingArticleView.swift
  Targets/UserInterface/Sources/Scenes/Searcing/SearchingArticleViewModel.swift
Labels: 🐞Bug, ⛔️Hotfix, ♻️Refactor

#203 [fix] LoginUser 제거 처리 및 불필요한 코드 주석처리, 삭제
  Targets/API/Resources/URLStrings.plist
  Targets/Domain/Sources/Entity/LoginUserData.swift
  Targets/Domain/Sources/Model/LoginModel.swift
  Targets/Ticlemoa/Sources/TiclemoaApp.swift
  Targets/UserInterface/Sources/ContentView.swift
  Targets/UserInterface/Sources/Login/LoginView.swift
  Targets/UserInterface/Sources/Login/LoginViewModel.swift
  Targets/UserInterface/Sources/Scenes/MainTab/MainTabView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageViewModel.swift
Labels: ♻️Refactor

#205 [fix] 티클모아 시작하기 버튼 하단 패딩변경
  Targets/UserInterface/Sources/Login/LoginView.swift
Labels: ♻️Refactor

#209 [Fix] 복붙(Paste) 권한 체크, 앱 구동 시 한번만 뜨도록 수정
  Targets/UserInterface/Sources/AddingLinkView/View/AddingLinkView.swift
  Targets/UserInterface/Sources/AddingLinkView/ViewModel/AddingLinkViewModel.swift
  Targets/UserInterface/Sources/Scenes/MainTab/MainTabView.swift
Labels: 🐞Bug

#210 [Feature] 프로필 설정 화면 진입시 키보드 자동 포커스
  Targets/UserInterface/Sources/Scenes/MyPage/ProfileSetting/ProfileSettingView.swift
Labels: ⚡️Feature

#213 [Feature] 아티클 수정하기 시, 아티클 추가되지 않고 수정되도록 함
  Targets/UserInterface/Sources/AddingLinkView/View/AddingLinkView.swift
  Targets/UserInterface/Sources/AddingLinkView/ViewModel/AddingLinkViewModel.swift
Labels: 🐞Bug

#214 [Fix] 닉네임을 변경할 시 앱이 꺼지는 버그 해결
  Targets/Domain/Sources/Model/LoginModel.swift
Labels: 🐞Bug

#215 [Fix] 검색 화면에서 하단 탭바 보이지 않게 처리
  Targets/UserInterface/Sources/Scenes/MainTab/MainTabView.swift
Labels: 🐞Bug

#218 [fix] 최근 검색어 중복 제거
  Targets/UserInterface/Sources/Scenes/Searcing/SearchingArticleView.swift
Labels: ♻️Refactor

#219 [Feature] 계정 삭제시 삭제되는 아티클 갯수 표시
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageViewModel.swift
Labels: ⚡️Feature

#222 [Feature] 마이페이지 상단에 Ticlemoa 로고 제거
  Targets/UserInterface/Sources/Home/HomeView.swift
Labels: ⚡️Feature

#226 [Feature] 태그 관리 기능(태그별 아티클 삭제) 구현
  Targets/Domain/Sources/Model/ArticleModel.swift
  Targets/Domain/Sources/Model/TagModel.swift
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/tag_empty.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/tag_empty.imageset/tag_empty.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/tag_empty.imageset/tag_empty@2x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/Images/tag_empty.imageset/tag_empty@3x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/article_empty.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/article_empty.imageset/article_empty.png
  Targets/Ticlemoa/Resources/Assets.xcassets/article_empty.imageset/article_empty@2x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/article_empty.imageset/article_empty@3x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/black_add.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/black_add.imageset/black_add.png
  Targets/Ticlemoa/Resources/Assets.xcassets/black_add.imageset/black_add@2x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/black_add.imageset/black_add@3x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/meat_ball.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/meat_ball.imageset/meat_ball.png
  Targets/Ticlemoa/Resources/Assets.xcassets/meat_ball.imageset/meat_ball@2x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/meat_ball.imageset/meat_ball@3x.png
  Targets/UserInterface/Sources/Home/HomeArticle/ArticleRow.swift
  Targets/UserInterface/Sources/Home/HomeView.swift
  Targets/UserInterface/Sources/Home/HomeViewModel.swift
  Targets/UserInterface/Sources/Scenes/TagManaging/ArticleManagingListRow.swift
  Targets/UserInterface/Sources/Scenes/TagManaging/ArticleManagingListView.swift
  Targets/UserInterface/Sources/Scenes/TagManaging/TagManagingView.swift
  Targets/UserInterface/Sources/TagManagingView.swift
Labels: ⚡️Feature

#224 [Fix] TagModel 데이터 바인딩
  Targets/UserInterface/Sources/Home/HomeViewModel.swift
Labels: 🐞Bug

#228 [Feature] 기본 프로필 이미지 적용
  Targets/Ticlemoa/Resources/Assets.xcassets/DefaultProfileImage.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/DefaultProfileImage.imageset/icon.jpg
  Targets/Ticlemoa/Resources/Assets.xcassets/DefaultProfileImage.imageset/icon@2x.jpg
  Targets/Ticlemoa/Resources/Assets.xcassets/DefaultProfileImage.imageset/icon@3x.jpg
  Targets/UserInterface/Sources/Nextup/DefaultProfileView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/ProfileSetting/ProfileSettingView.swift
Labels: ⚡️Feature

#232 [refactor] 네이밍 수정 및 불필요한 정보 제거, 키보드
  Targets/API/Sources/Request/Article/CreateArticleRequest.swift
  Targets/Domain/Sources/Model/ArticleModel.swift
  Targets/UserInterface/Sources/AddingLinkView/AddingLinkView.swift
  Targets/UserInterface/Sources/Home/HomeArticle/HomeArticleListModel.swift
  Targets/UserInterface/Sources/Home/HomeView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/MyPageViewModel.swift
  Targets/UserInterface/Sources/Scenes/MyPage/ProfileSetting/ProfileSettingView.swift
  Targets/UserInterface/Sources/Scenes/MyPage/ProfileSetting/ProfileSettingViewModel.swift
  Targets/UserInterface/Sources/Utils/Extensions/DateFormatter+Extensions.swift
Labels: ♻️Refactor

#233 [Feature] 홈 화면 태그 가로스크롤 기능 적용
  Targets/Ticlemoa/Resources/Assets.xcassets/arrow.down.imageset/Contents.json
  Targets/Ticlemoa/Resources/Assets.xcassets/arrow.down.imageset/Vector.png
  Targets/Ticlemoa/Resources/Assets.xcassets/arrow.down.imageset/Vector@2x.png
  Targets/Ticlemoa/Resources/Assets.xcassets/arrow.down.imageset/Vector@3x.png
  Targets/UserInterface/Sources/Home/HomeView.swift
  Targets/UserInterface/Sources/Home/HomeViewModel.swift
Labels: ⚡️Feature

#241 [Feature] 태그 관리 화면으로 넘어가는 기능
  Targets/DepromeetTiclemoa/Resources/Assets.xcassets/arrow.down.imageset/Contents.json
  Targets/DepromeetTiclemoa/Resources/Assets.xcassets/arrow.down.imageset/Vector.png
  Targets/DepromeetTiclemoa/Resources/Assets.xcassets/arrow.down.imageset/Vector@2x.png
  Targets/DepromeetTiclemoa/Resources/Assets.xcassets/arrow.down.imageset/Vector@3x.png
  Targets/DepromeetTiclemoa/Resources/Assets.xcassets/arrow.up.imageset/Contents.json
  Targets/DepromeetTiclemoa/Resources/Assets.xcassets/arrow.up.imageset/Vector.png
  Targets/DepromeetTiclemoa/Resources/Assets.xcassets/arrow.up.imageset/Vector@2x.png
  Targets/DepromeetTiclemoa/Resources/Assets.xcassets/arrow.up.imageset/Vector@3x.png
  Targets/DepromeetTiclemoa/Resources/Assets.xcassets/tagArrow.right.imageset/Contents.json
  Targets/DepromeetTiclemoa/Resources/Assets.xcassets/tagArrow.right.imageset/Vector.png
  Targets/DepromeetTiclemoa/Resources/Assets.xcassets/tagArrow.right.imageset/Vector@2x.png
  Targets/DepromeetTiclemoa/Resources/Assets.xcassets/tagArrow.right.imageset/Vector@3x.png
  Targets/UserInterface/Sources/Home/HomeView.swift
  Targets/UserInterface/Sources/Home/HomeViewModel.swift
Labels: ⚡️Feature

#245 [Feature] 토스트 메시지 추가
  Targets/UserInterface/Sources/AddingLinkView/AddingLinkView.swift
  Targets/UserInterface/Sources/Scenes/TagManaging/ArticleManagingListView.swift
  Targets/UserInterface/Sources/Utils/Components/ToastMessage.swift
Labels: ⚡️Feature
